### ISSUE TITLE
"Too many arguments" error when starting iJavaScript kernel

### ISSUE THREAD

**Issue by BoPeng** [n-riesco/ijavascript#108]
I got the following error message when I tried to start a iJavaScript kernel on a Mac machine:

```
$ jupyter notebook
[W 00:45:22.583 NotebookApp] server_extensions is deprecated, use nbserver_extensions
[I 00:45:23.260 NotebookApp] The port 8888 is already in use, trying another port.
[I 00:45:25.355 NotebookApp] hide_code: Attempting to load hid_code export handler extensions.
[I 00:45:25.357 NotebookApp] hide_code: Hide_code export handler extensions loaded.
[I 00:45:25.389 NotebookApp] [jupyter_nbextensions_configurator] enabled 0.2.5
[I 00:45:25.397 NotebookApp] Serving notebooks from local directory: /Users/bpeng1/sos/test/JavaScript
[I 00:45:25.398 NotebookApp] 0 active kernels
[I 00:45:25.398 NotebookApp] The Jupyter Notebook is running at: http://localhost:8889/?token=c826d08f19a864c15bbac38a73d2d517e4e4ebbe6be111ac
[I 00:45:25.398 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 00:45:25.400 NotebookApp]

    Copy/paste this URL into your browser when you connect for the first time,
    to login with a token:
        http://localhost:8889/?token=c826d08f19a864c15bbac38a73d2d517e4e4ebbe6be111ac
[I 00:45:25.725 NotebookApp] Accepting one-time-token-authenticated connection from ::1
[I 00:45:30.288 NotebookApp] Creating new notebook in
[I 00:45:31.055 NotebookApp] Kernel started: 21c427f7-f9a8-4e43-aeda-ff34e6bda84a
[W 00:45:41.110 NotebookApp] Timeout waiting for kernel_info reply from 21c427f7-f9a8-4e43-aeda-ff34e6bda84a
KERNEL: ARGV: [ '/usr/local/Cellar/node/7.8.0/bin/node',
  '/usr/local/Cellar/node/7.8.0/libexec/npm/bin/ijskernel',
  '--debug',
  '--hide-undefined',
  '2',
  '/var/folders/ys/gnzk0qbx5wbdgm531v82xxljv5yqy8/T/tmp3xhmu6x8.json',
  '--protocol=5.0' ]
Usage: node kernel.js [--debug] [--hide-undefined] [--protocol=Major[.minor[.patch]]] [--session-working-dir=path] [--show-undefined] [--startup-script=path] connection_file
/usr/local/Cellar/node/7.8.0/libexec/npm/lib/node_modules/ijavascript/lib/kernel.js:190
        throw e;
        ^

Error: Error: too many arguments
    at /usr/local/Cellar/node/7.8.0/libexec/npm/lib/node_modules/ijavascript/lib/kernel.js:175:23
    at Array.forEach (native)
    at parseCommandArguments (/usr/local/Cellar/node/7.8.0/libexec/npm/lib/node_modules/ijavascript/lib/kernel.js:160:31)
    at Object.<anonymous> (/usr/local/Cellar/node/7.8.0/libexec/npm/lib/node_modules/ijavascript/lib/kernel.js:46:14)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
KERNEL: ARGV: [ '/usr/local/Cellar/node/7.8.0/bin/node',
  '/usr/local/Cellar/node/7.8.0/libexec/npm/bin/ijskernel',
  '--debug',
  '--hide-undefined',
  '2',
  '/var/folders/ys/gnzk0qbx5wbdgm531v82xxljv5yqy8/T/tmpz6xwxwyf.json',
  '--protocol=5.0' ]
Usage: node kernel.js [--debug] [--hide-undefined] [--protocol=Major[.minor[.patch]]] [--session-working-dir=path] [--show-undefined] [--startup-script=path] connection_file
/usr/local/Cellar/node/7.8.0/libexec/npm/lib/node_modules/ijavascript/lib/kernel.js:190
        throw e;
        ^
```

It is strange because I was able to use iJavaScript and I cannot recall what change I have made to the system to trigger this error (upgrade Jupyter?).

**Comment by n-riesco** [comment]
Let's check first that IJavascript's kernelspec is installed properly.
Please, could you run the following command and post the output?

```
$ jupyter kernelspec list --json
```

**Comment by BoPeng** [comment]
```
$ jupyter kernelspec list --json
{
  "kernelspecs": {
    "bash": {
      "resource_dir": "/Users/bpeng1/Library/Jupyter/kernels/bash",
      "spec": {
        "argv": [
          "/Users/bpeng1/anaconda/bin/python",
          "-m",
          "bash_kernel",
          "-f",
          "{connection_file}"
        ],
        "env": {
          "PS1": "$"
        },
        "display_name": "Bash",
        "language": "bash"
      }
    },
    "javascript": {
      "resource_dir": "/Users/bpeng1/Library/Jupyter/kernels/javascript",
      "spec": {
        "argv": [
          "ijskernel",
          "--debug",
          "--hide-undefined",
          "2",
          "{connection_file}",
          "--protocol=5.0"
        ],
        "env": {},
        "display_name": "Javascript (Node.js)",
        "language": "javascript"
      }
    },
    "python2": {
      "resource_dir": "/Users/bpeng1/Library/Jupyter/kernels/python2",
      "spec": {
        "argv": [
          "/Users/bpeng1/anaconda/envs/ipykernel_py2/bin/python",
          "-m",
          "ipykernel",
          "-f",
          "{connection_file}"
        ],
        "env": {},
        "display_name": "Python 2",
        "language": "python"
      }
    },
    "rik_local_remote": {
      "resource_dir": "/Users/bpeng1/Library/Jupyter/kernels/rik_local_remote",
      "spec": {
        "argv": [
          "/Users/bpeng1/anaconda/bin/python",
          "-m",
          "remote_ikernel",
          "--interface",
          "local",
          "--kernel_cmd",
          "ipython kernel -f {host_connection_file}",
          "{connection_file}"
        ],
        "env": {},
        "display_name": "Local remote",
        "language": ""
      }
    },
    "ir": {
      "resource_dir": "/Users/bpeng1/anaconda/share/jupyter/kernels/ir",
      "spec": {
        "argv": [
          "R",
          "--slave",
          "-e",
          "IRkernel::main()",
          "--args",
          "{connection_file}"
        ],
        "env": {},
        "display_name": "R",
        "language": "R"
      }
    },
    "python3": {
      "resource_dir": "/Users/bpeng1/anaconda/share/jupyter/kernels/python3",
      "spec": {
        "argv": [
          "python",
          "-m",
          "ipykernel_launcher",
          "-f",
          "{connection_file}"
        ],
        "env": {},
        "display_name": "Python 3",
        "language": "python"
      }
    },
    "sos": {
      "resource_dir": "/Users/bpeng1/anaconda/share/jupyter/kernels/sos",
      "spec": {
        "argv": [
          "python",
          "-m",
          "sos.jupyter.kernel",
          "-f",
          "{connection_file}"
        ],
        "env": {},
        "display_name": "SoS",
        "language": "sos"
      }
    }
  }
}
```

**Comment by n-riesco** [comment]
OK, so the problem is in the the kernelspec (for some reason, it has "2" as one of the arguments to pass to the IJavascript kernel).

What method did you use to install IJavascript's kernelspec?

**Comment by BoPeng** [comment]
That is really strange because I would not have entered that `2` manually. I tried `ijsinstall`, `ijsinstall --local`, and had tried to fix  `$PATH` because the kernel would not start if `ijskernel` is not in `$PATH`, and `/usr/local/Cellar/node/7.8.0/libexec/npm/bin//` is not in my `%PATH` by default.

Now I have tried again to do `ijsinstall` etc but the `2` disappeared.

**Comment by n-riesco** [comment]
By the way, if `ijskernel` and `node` aren't in your `PATH`, you can install the kernelspec with full paths by running:

```
ijsinstall --spec-path=full
```

**Comment by BoPeng** [comment]
Thanks for the tip, I will install `iJavaScript` with full `--spec-path` to avoid `$PATH` problem. I am closing the ticket now and will re-open it if I can reproduce it.
