### ISSUE TITLE
question: code cell output undefined

### ISSUE THREAD

**Issue by lab4quant** [n-riesco/ijavascript#109]
Hello, please refer to below code, after execution the output is `undefined`

However, if I add a new cell and put `output` as code then execute, it's printing the `output` variable value. BTW, I also tried `console.log(output)`, it printed value in the input cell, the output cell is still `undefined`

How can I yield `output` value from only one code cell? thanks!

```js
var args = [];
args.push("XX");
args.push([["2011","4"],["2012","8042"]]);
var output, error;
myfunction.apply(undefined,args).then(result=>output=result).catch(e=>error=e);
output || error
```

**Comment by lab4quant** [comment]
sorry for the trouble, i realized this is due to the promise, first time to yield variable, it was not set yet

**Comment by n-riesco** [comment]
@lab4quant IJavascript provides an interface to create a cell's output asynchronously. I have adapted your example to show how:

```js
// In[1]:
var util = require("util");

var args = [];
args.push("XX");
args.push([["2011","4"],["2012","8042"]]);

function myfunction() {
    if (this === global) return Promise.resolve(util.inspect(arguments));
    else throw new Error(util.inspect(this));
}
// Out[1]: 2

// In[2]:
var $2 = $$;
$2.async();
myfunction.apply(undefined, args).then($2.sendResult).catch($2.sendError);
// Out[2]: '{ \'0\': \'XX\', \'1\': [ [ \'2011\', \'4\' ], [ \'2012\', \'8042\' ] ] }'

// In[3]:
var $3 = $$;
$3.async();
myfunction.apply(args).then($3.sendResult).catch($3.sendError);
// Out[3]:
// Error: [ 'XX', [ [ '2011', '4' ], [ '2012', '8042' ] ] ]
//     at Array.myfunction (evalmachine.<anonymous>:9:16)
//     at evalmachine.<anonymous>:5:12
//     at Object.exports.runInThisContext (vm.js:54:17)
//     at run ([eval]:617:19)
//     at onRunRequest ([eval]:388:22)
//     at onMessage ([eval]:356:17)
//     at emitTwo (events.js:87:13)
//     at process.emit (events.js:172:7)
//     at handleMessage (internal/child_process.js:689:10)
//     at Pipe.channel.onread (internal/child_process.js:440:11)
```

See [here](https://github.com/n-riesco/ijavascript/blob/dev/doc/async.ipynb) for more details.

**Comment by lab4quant** [comment]
@n-riesco , thank you for your update, it's very helpful!
