### ISSUE TITLE
Sudo install with node@8.9.4 and npm@5.7.1

### ISSUE THREAD

**Issue by alvarosainzpardo** [n-riesco/ijavascript#147]
In Ubuntu 16.04 when I try `$ sudo npm install -g ijavascript` I get this error:

```bash
/usr/bin/ijs -> /usr/lib/node_modules/ijavascript/bin/ijavascript.js
/usr/bin/ijsconsole -> /usr/lib/node_modules/ijavascript/bin/ijsconsole.js
/usr/bin/ijsinstall -> /usr/lib/node_modules/ijavascript/bin/ijsinstall.js
/usr/bin/ijsnotebook -> /usr/lib/node_modules/ijavascript/bin/ijsnotebook.js
/usr/bin/ijskernel -> /usr/lib/node_modules/ijavascript/lib/kernel.js

> zeromq@4.6.0 install /usr/lib/node_modules/ijavascript/node_modules/zeromq
> node scripts/prebuild-install.js || (node scripts/preinstall.js && node-gyp rebuild)


prebuild-install info begin Prebuild-install version 2.5.1
prebuild-install info looking for local prebuild @ prebuilds/zeromq-v4.6.0-node-v57-linux-x64.tar.gz
prebuild-install info looking for cached prebuild @ /home/asainz/.npm/_prebuilds/https-github.com-zeromq-zeromq.js-releases-download-v4.6.0-zeromq-v4.6.0-node-v57-linux-x64.tar.gz
prebuild-install info found cached prebuild
prebuild-install info unpacking @ /home/asainz/.npm/_prebuilds/https-github.com-zeromq-zeromq.js-releases-download-v4.6.0-zeromq-v4.6.0-node-v57-linux-x64.tar.gz
prebuild-install WARN install EACCES: permission denied, mkdir '/usr/lib/node_modules/ijavascript/node_modules/zeromq/build'

fs.js:885
  return binding.mkdir(pathModule._makeLong(path),
                 ^

Error: EACCES: permission denied, mkdir '/usr/lib/node_modules/ijavascript/node_modules/zeromq/zmq'
    at Object.fs.mkdirSync (fs.js:885:18)
    at Object.<anonymous> (/usr/lib/node_modules/ijavascript/node_modules/zeromq/scripts/preinstall.js:89:8)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Function.Module.runMain (module.js:684:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! zeromq@4.6.0 install: `node scripts/prebuild-install.js || (node scripts/preinstall.js && node-gyp rebuild)`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the zeromq@4.6.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/asainz/.npm/_logs/2018-02-28T15_19_53_099Z-debug.log
```
Any ideas? Thank you!

**Comment by n-riesco** [comment]
See #146 (I guess that what you're after is `sudo npm install -g --unsafe-perm ijavascript`)
