### ISSUE TITLE
Error: Address in use from zmq

### ISSUE THREAD

**Issue by barik** [n-riesco/ijavascript#180]
When I attempt to restart a Jupyter kernel from within the jupyter notebook GUI (`Kernel > Restart`) on Windows 10 I receive the following error in the console:

```
c:\opt\nvm\v11.6.0\node_modules\ijavascript\node_modules\zeromq\lib\index.js:451
  this._zmq.bindSync(addr);
            ^

Error: Address in use
    at exports.Socket.Socket.bindSync (c:\opt\nvm\v11.6.0\node_modules\ijavascript\node_modules\zeromq\lib\index.js:451:13)
    at Kernel._bindSockets (c:\opt\nvm\v11.6.0\node_modules\ijavascript\node_modules\jp-kernel\lib\jp-kernel.js:262:19)
    at new Kernel (c:\opt\nvm\v11.6.0\node_modules\ijavascript\node_modules\jp-kernel\lib\jp-kernel.js:244:10)
    at Object.<anonymous> (c:\opt\nvm\v11.6.0\node_modules\ijavascript\lib\kernel.js:69:14)
    at Module._compile (internal/modules/cjs/loader.js:721:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:732:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:774:12)
```

I'm not sure how to isolate this problem, but I suspect it is Windows-specific somehow. Versions of things:

* ijs: 5.0.20
* node: 11.6.0
* jupyter: 4.4.0

I followed the instructions from the [zeromq NPM package page](https://www.npmjs.com/package/zeromq) to allow ZMQ to compile from source (`Windows > Option 2`).

**Comment by n-riesco** [comment]
My guess is that Jupyter Notebook tries to kill the kernel and fails.

I'll find a Windows box and see if I can debug the issue.

Regardless of the cause, I'm thinking of adding a flag to workaround this issue and let the kernel die when it receives a restart request; e.g.:
```
ijsinstall --kill-on-restart
```
