### ISSUE TITLE
Permission issues when install ijavascript

### ISSUE THREAD

**Issue by dclong** [n-riesco/ijavascript#185]
Running `sudo npm install -g ijavascript` gives me the following error message. 
```
prebuild-install WARN install EACCES: permission denied, access '/home/chdu/.npm'

fs.js:115
    throw err;
    ^

Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/ijavascript/node_modules/zeromq/zmq'
    at Object.mkdirSync (fs.js:753:3)
    at Object.<anonymous> (/usr/local/lib/node_modules/ijavascript/node_modules/zeromq/scripts/preinstall.js:89:8)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! zeromq@4.6.0 install: `node scripts/prebuild-install.js || (node scripts/preinstall.js && node-gyp rebuild)`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the zeromq@4.6.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/chdu/.npm/_logs/2019-01-31T20_23_51_861Z-debug.log
```

**Comment by n-riesco** [comment]
@dclong If you really need a `sudo` install, `npm` version 5 and above require the flag `--unsafe-perm`, like this:

```
sudo npm install -g --unsafe-perm ijavascript
```

Let's continue the conversation on #146.
