### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'ijskernel': 'ijskernel'

### ISSUE THREAD

**Issue by EasonWang01** [n-riesco/ijavascript#195]
```
ijs --version: 5.0.20
pip3 -V: pip 19.0.3 (python 3.7)
JuypterLab version: 0.35.4
```

Error:

<img width="454" alt="螢幕快照 2019-05-23 下午1 15 06" src="https://user-images.githubusercontent.com/11001914/58227284-ccec1d00-7d5c-11e9-9e31-6ae290c64600.png">

```
Error Starting Kernel
Traceback (most recent call last):
  File "/Users/yicheng/anaconda3/lib/python3.7/site-packages/tornado/web.py", line 1699, in _execute
    result = await result
  File "/Users/yicheng/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 736, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/Users/yicheng/anaconda3/lib/python3.7/site-packages/notebook/services/sessions/handlers.py", line 73, in post
    type=mtype))
  File "/Users/yicheng/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 729, in run
    value = future.result()
  File "/Users/yicheng/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 736, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/Users/yicheng/anaconda3/lib/python3.7/site-packages/notebook/services/sessions/sessionmanager.py", line 79, in create_session
    kernel_id = yield self.start_kernel_for_session(session_id, path, name, type, kernel_name)
  File "/Users/yicheng/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 729, in run
    value = future.result()
  File "/Users/yicheng/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 736, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/Users/yicheng/anaconda3/lib/python3.7/site-packages/notebook/services/sessions/sessionmanager.py", line 92, in start_kernel_for_session
    self.kernel_manager.start_kernel(path=kernel_path, kernel_name=kernel_name)
  File "/Users/yicheng/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 729, in run
    value = future.result()
  File "/Users/yicheng/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 209, in wrapper
    yielded = next(result)
  File "/Users/yicheng/anaconda3/lib/python3.7/site-packages/notebook/services/kernels/kernelmanager.py", line 160, in start_kernel
    super(MappingKernelManager, self).start_kernel(**kwargs)
  File "/Users/yicheng/anaconda3/lib/python3.7/site-packages/jupyter_client/multikernelmanager.py", line 110, in start_kernel
    km.start_kernel(**kwargs)
  File "/Users/yicheng/anaconda3/lib/python3.7/site-packages/jupyter_client/manager.py", line 259, in start_kernel
    **kw)
  File "/Users/yicheng/anaconda3/lib/python3.7/site-packages/jupyter_client/manager.py", line 204, in _launch_kernel
    return launch_kernel(kernel_cmd, **kw)
  File "/Users/yicheng/anaconda3/lib/python3.7/site-packages/jupyter_client/launcher.py", line 138, in launch_kernel
    proc = Popen(cmd, **kwargs)
  File "/Users/yicheng/anaconda3/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/Users/yicheng/anaconda3/lib/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'ijskernel': 'ijskernel'

OK
```

**Comment by n-riesco** [comment]
The error message is telling us that `npm` in your machine installs binaries in a folder not included in your `PATH`.

IJavascript provides an option to install a kernelspec that workarounds this issue. Please, could you test if the following command works for you?
```
ijsinstall --spec-path=full
```

**Comment by n-riesco** [comment]
@EasonWang01 I'm assuming the solution above solved the issue. Please, feel free to reopen if the issue is still present.
