### ISSUE TITLE
Update install instructions for Ubuntu

### ISSUE THREAD

**Issue by KHarrison99** [n-riesco/ijavascript#202]
I try to install ijavascript on my Linux Mint machine, but seem to have issues. Not sure why

npm -v:
`3.5.2`

node -v
`v8.10.0`

Here is output from sudo npm install -g ijavascript
```
/usr/local/bin/ijs -> /usr/local/lib/node_modules/ijavascript/bin/ijavascript.js
/usr/local/bin/ijsconsole -> /usr/local/lib/node_modules/ijavascript/bin/ijsconsole.js
/usr/local/bin/ijsinstall -> /usr/local/lib/node_modules/ijavascript/bin/ijsinstall.js
/usr/local/bin/ijskernel -> /usr/local/lib/node_modules/ijavascript/lib/kernel.js
/usr/local/bin/ijsnotebook -> /usr/local/lib/node_modules/ijavascript/bin/ijsnotebook.js

> zeromq@5.1.0 install /usr/local/lib/node_modules/ijavascript/node_modules/zeromq
> node scripts/prebuild-install.js || (node scripts/preinstall.js && node-gyp rebuild)


prebuild-install WARN install EACCES: permission denied, access '/home/k/.npm'

Building libzmq for linux
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether UID '65534' is supported by ustar format... yes
checking whether GID '1000' is supported by ustar format... yes
checking how to create a ustar tar archive... gnutar
checking whether make supports nested variables... (cached) yes
checking for gcc... gcc
checking whether the C compiler works... no
configure: error: in `/usr/local/lib/node_modules/ijavascript/node_modules/zeromq/zmq/zeromq-4.2.2':
configure: error: C compiler cannot create executables
See `config.log' for more details
child process exited with code 77
make: Entering directory '/usr/local/lib/node_modules/ijavascript/node_modules/zeromq/build'
  CXX(target) Release/obj.target/zmq/binding.o
make: g++: Command not found
zmq.target.mk:95: recipe for target 'Release/obj.target/zmq/binding.o' failed
make: *** [Release/obj.target/zmq/binding.o] Error 127
make: Leaving directory '/usr/local/lib/node_modules/ijavascript/node_modules/zeromq/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/share/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 4.15.0-54-generic
gyp ERR! command "/usr/bin/node" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/ijavascript/node_modules/zeromq
gyp ERR! node -v v8.10.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
/usr/local/lib
└── (empty)

npm ERR! Linux 4.15.0-54-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "-g" "ijavascript"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE

npm ERR! zeromq@5.1.0 install: `node scripts/prebuild-install.js || (node scripts/preinstall.js && node-gyp rebuild)`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the zeromq@5.1.0 install script 'node scripts/prebuild-install.js || (node scripts/preinstall.js && node-gyp rebuild)'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the zeromq package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/prebuild-install.js || (node scripts/preinstall.js && node-gyp rebuild)
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs zeromq
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls zeromq
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/k/Downloads/npm-debug.log
npm ERR! code 1
```
Thanks for taking the time to read! Let me know if I missed anything, I tried to attach npm-debug.log from the location shown in the error. But it does not appear to be in that directory, searched for it but no luck.

**Comment by n-riesco** [comment]
The installation instructions need updating.

If IJavascript will only be accessed by your user, the instructions are:

```
sudo apt-get install nodejs npm jupyter-notebook
npm config set prefix $HOME
npm install -g ijavascript
ijsinstall
```
(if `~/bin` folder didn't exist before, after running this instructions, you may need to log out and back in for `~/bin` to be added to your `PATH`).

If IJavascript will be accessible by other users, then:

```
sudo apt-get install nodejs npm jupyter-notebook
sudo npm install -g --unsafe-perm ijavascript
sudo ijsinstall --install=global
```
