### ISSUE TITLE
Kernel error! 

### ISSUE THREAD

**Issue by MajidHakimi** [n-riesco/ijavascript#218]
Hi 
I use Anaconda Distribution and according install instruction I run bellow instruction 

conda install nodejs
npm install -g `ijavascript`
ijsinstall

But in install I get bellow error
![1](https://user-images.githubusercontent.com/18713893/78421609-41c2ff80-766e-11ea-9d9b-be704e636737.png)

AFTER CONFIRM I GET ERROR

![2](https://user-images.githubusercontent.com/18713893/78421645-759e2500-766e-11ea-8493-695ee559227f.png)

SEE ERROR BY CMD and WINDOWS

![3](https://user-images.githubusercontent.com/18713893/78421664-98c8d480-766e-11ea-8a4c-fad742588d34.png)

![4](https://user-images.githubusercontent.com/18713893/78421680-c281fb80-766e-11ea-89ce-f369e3d2a912.png)

after all instruction I have Nodejs in notebook BUT the kernel has ERROR 

![5](https://user-images.githubusercontent.com/18713893/78421723-155bb300-766f-11ea-8c82-2b054e836acb.png)

![6](https://user-images.githubusercontent.com/18713893/78421724-1856a380-766f-11ea-8b2d-4a53515cffed.png)

kernel log 

`
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\tornado\web.py", line 1592, in _execute
    result = yield result
  File "C:\ProgramData\Anaconda3\lib\site-packages\tornado\gen.py", line 1133, in run
    value = future.result()
  File "C:\ProgramData\Anaconda3\lib\site-packages\tornado\gen.py", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "C:\ProgramData\Anaconda3\lib\site-packages\notebook\services\sessions\handlers.py", line 73, in post
    type=mtype))
  File "C:\ProgramData\Anaconda3\lib\site-packages\tornado\gen.py", line 1133, in run
    value = future.result()
  File "C:\ProgramData\Anaconda3\lib\site-packages\tornado\gen.py", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "C:\ProgramData\Anaconda3\lib\site-packages\notebook\services\sessions\sessionmanager.py", line 79, in create_session
    kernel_id = yield self.start_kernel_for_session(session_id, path, name, type, kernel_name)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tornado\gen.py", line 1133, in run
    value = future.result()
  File "C:\ProgramData\Anaconda3\lib\site-packages\tornado\gen.py", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "C:\ProgramData\Anaconda3\lib\site-packages\notebook\services\sessions\sessionmanager.py", line 92, in start_kernel_for_session
    self.kernel_manager.start_kernel(path=kernel_path, kernel_name=kernel_name)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tornado\gen.py", line 1133, in run
    value = future.result()
  File "C:\ProgramData\Anaconda3\lib\site-packages\tornado\gen.py", line 326, in wrapper
    yielded = next(result)
  File "C:\ProgramData\Anaconda3\lib\site-packages\notebook\services\kernels\kernelmanager.py", line 160, in start_kernel
    super(MappingKernelManager, self).start_kernel(**kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\jupyter_client\multikernelmanager.py", line 110, in start_kernel
    km.start_kernel(**kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\jupyter_client\manager.py", line 259, in start_kernel
    **kw)
  File "C:\ProgramData\Anaconda3\lib\site-packages\jupyter_client\manager.py", line 204, in _launch_kernel
    return launch_kernel(kernel_cmd, **kw)
  File "C:\ProgramData\Anaconda3\lib\site-packages\jupyter_client\launcher.py", line 128, in launch_kernel
    proc = Popen(cmd, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\subprocess.py", line 756, in __init__
    restore_signals, start_new_session)
  File "C:\ProgramData\Anaconda3\lib\subprocess.py", line 1155, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified

`

 Please help me how can I solve it

**Comment by n-riesco** [comment]
I don't see any error specific to IJavascript. The warning message `"The environment is inconsistent"` suggests your conda installation needs updating (I only use conda for testing, so I'm just guessing).

Have you tried something like `conda update --all` or `conda update -n menv --all`?

**Comment by MajidHakimi** [comment]
I tried to update but I get error connection I disable Kaspersky and I had some problem , I reinstall Anaconda and my problem solved . 
I think according your mention my problem was updated Anaconda
