### ISSUE TITLE
Connection failed after continual attempts of automatic restart javascript(node.js) kernel in jupyter notebook

### ISSUE THREAD

**Issue by santokalayil** [n-riesco/ijavascript#219]
Connection failed after continual attempts of automatic restart javascript(node.js) kernel in jupyter notebook. I use python 3, julia kernels as well in jupyter.. Only Javascript kernel fails; others works perfect. I use linux machine..

====== THE ERROR =====
Connection failed
A connection to the notebook server could not be established. The notebook will continue trying to reconnect. Check your network connection or notebook server configuration.
-------------------------------------------------------------------------------------------

Connecting to: tcp://127.0.0.1:49371
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module '../build/Release/zmq.node'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/ijavascript/node_modules/zeromq/lib/index.js:6:11)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
[W 01:57:58.764 NotebookApp] KernelRestarter: restart failed
[W 01:57:58.764 NotebookApp] Kernel 19261f06-ea21-4ab3-8246-ddd5070861f5 died, removing from map.

**Comment by n-riesco** [comment]
it looks like like the binary module for zmq is either missing or obsolote. Uninstalling and installing IJavascript should fix the issue.

**Comment by n-riesco** [comment]
Closing for lack of feedback and being unable to reproduce.
