### ISSUE TITLE
MacOS install - Seems to need XCode installed

### ISSUE THREAD

**Issue by jamesnyika** [n-riesco/ijavascript#222]
Fails with exception at the NPM installation step  - Does it need XCode to complete ? 
```
No receipt for 'com.apple.pkg.CLTools_Executables' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLILeo' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLI' found at '/'.

gyp: **No Xcode or CLT version detected!**
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Darwin 19.5.0
gyp ERR! command "/usr/local/Cellar/node/13.13.0_1/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/ijavascript/node_modules/zeromq
gyp ERR! node -v v13.13.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! zeromq@5.2.0 install: `node scripts/prebuild-install.js || (node scripts/preinstall.js && node-gyp rebuild)`
npm ERR! Exit status 1
```

**Comment by n-riesco** [comment]
Unfortunately, `zeromq` doesn't distribute pre-built binaries of `zeromq@5` for the newer versions of node and electron. The requirements to build the binary can be found [here](https://github.com/nodejs/node-gyp#on-macos).

**Comment by jamesnyika** [comment]
Yeah. Well.. for those who need this resolved, you just have to install Mac Xcode,and be sure to actually start it up.. because there is some additional configuration it does. Once done, rerun the command to install ijavascript using npm..
