### ISSUE TITLE
Error running `jupyter kernelspec install

### ISSUE THREAD

**Issue by henryfoster** [n-riesco/ijavascript#224]
Ubuntu20.04 jupiter-notebook starts the notebook properly but this command produces this error:

sudo ijsinstall

```
Error running `jupyter kernelspec install --replace /tmp/01e120f82d4ee4052a1f25ed2fa81c7b/javascript --user`
Error: Command failed: jupyter kernelspec install --replace /tmp/01e120f82d4ee4052a1f25ed2fa81c7b/javascript --user
Traceback (most recent call last):
  File "/usr/bin/jupyter", line 11, in <module>
    load_entry_point('jupyter-core==4.6.3', 'console_scripts', 'jupyter')()
  File "/usr/lib/python3/dist-packages/jupyter_core/command.py", line 247, in main
    command = _jupyter_abspath(subcommand)
  File "/usr/lib/python3/dist-packages/jupyter_core/command.py", line 133, in _jupyter_abspath
    raise Exception(
Exception: Jupyter command `jupyter-kernelspec` not found.

Traceback (most recent call last):
  File "/usr/bin/jupyter", line 11, in <module>
    load_entry_point('jupyter-core==4.6.3', 'console_scripts', 'jupyter')()
  File "/usr/lib/python3/dist-packages/jupyter_core/command.py", line 247, in main
    command = _jupyter_abspath(subcommand)
  File "/usr/lib/python3/dist-packages/jupyter_core/command.py", line 133, in _jupyter_abspath
    raise Exception(
Exception: Jupyter command `jupyter-kernelspec` not found.

```

**Comment by n-riesco** [comment]
Ubuntu 20.04 provides `jupyter-kernelspec` in the package `jupyter-client`. Installing this package should fix the issue: `sudo apt install jupyter-client`.

**Comment by henryfoster** [comment]
Thanks this fixed my issue
