### ISSUE TITLE
I can't do anything for ijavascript

### ISSUE THREAD

**Issue by pcamateur** [n-riesco/ijavascript#226]
(base) [root@host2 lib]# /usr/local/bin/ijsnotebook --allow-root
[W 19:01:05.039 NotebookApp] WARNING: The notebook server is listening on all IP addresses and not using encryption. This is not recommended.
[I 19:01:05.078 NotebookApp] JupyterLab extension loaded from /root/anaconda3/lib/python3.7/site-packages/jupyterlab
[I 19:01:05.078 NotebookApp] JupyterLab application directory is /root/anaconda3/share/jupyter/lab
[I 19:01:05.080 NotebookApp] Serving notebooks from local directory: /usr/local/lib/node_modules/ijavascript/lib
[I 19:01:05.080 NotebookApp] The Jupyter Notebook is running at:
[I 19:01:05.081 NotebookApp] http://host2:8123/
[I 19:01:05.081 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[E 19:01:26.149 NotebookApp] Failed to run command:
    ['ijskernel', '--hide-undefined', '/root/.local/share/jupyter/runtime/kernel-1faa7d66-bf62-47b8-a3c2-ada658bee07f.json', '--protocol=5.1']
        PATH='/root/anaconda3/bin:/root/anaconda3/condabin:/usr/local/sbin:/sbin:/bin:/usr/sbin:/usr/bin:/root/bin'
        with kwargs:
    {'stdin': -1, 'stdout': None, 'stderr': None, 'cwd': '/usr/local/lib/node_modules/ijavascript/lib', 'start_new_session': True}
    
[E 19:01:26.150 NotebookApp] Uncaught exception POST /api/sessions (192.168.1.5)
    HTTPServerRequest(protocol='http', host='192.168.1.55:8123', method='POST', uri='/api/sessions', version='HTTP/1.1', remote_ip='192.168.1.5')
    Traceback (most recent call last):
      File "/root/anaconda3/lib/python3.7/site-packages/tornado/web.py", line 1699, in _execute
        result = await result
      File "/root/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
        yielded = self.gen.throw(*exc_info)  # type: ignore
      File "/root/anaconda3/lib/python3.7/site-packages/notebook/services/sessions/handlers.py", line 72, in post
        type=mtype))
      File "/root/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
        value = future.result()
      File "/root/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
        yielded = self.gen.throw(*exc_info)  # type: ignore
      File "/root/anaconda3/lib/python3.7/site-packages/notebook/services/sessions/sessionmanager.py", line 88, in create_session
        kernel_id = yield self.start_kernel_for_session(session_id, path, name, type, kernel_name)
      File "/root/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
        value = future.result()
      File "/root/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
        yielded = self.gen.throw(*exc_info)  # type: ignore
      File "/root/anaconda3/lib/python3.7/site-packages/notebook/services/sessions/sessionmanager.py", line 101, in start_kernel_for_session
        self.kernel_manager.start_kernel(path=kernel_path, kernel_name=kernel_name)
      File "/root/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
        value = future.result()
      File "/root/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 209, in wrapper
        yielded = next(result)
      File "/root/anaconda3/lib/python3.7/site-packages/notebook/services/kernels/kernelmanager.py", line 168, in start_kernel
        super(MappingKernelManager, self).start_kernel(**kwargs)
      File "/root/anaconda3/lib/python3.7/site-packages/jupyter_client/multikernelmanager.py", line 110, in start_kernel
        km.start_kernel(**kwargs)
      File "/root/anaconda3/lib/python3.7/site-packages/jupyter_client/manager.py", line 259, in start_kernel
        **kw)
      File "/root/anaconda3/lib/python3.7/site-packages/jupyter_client/manager.py", line 204, in _launch_kernel
        return launch_kernel(kernel_cmd, **kw)
      File "/root/anaconda3/lib/python3.7/site-packages/jupyter_client/launcher.py", line 138, in launch_kernel
        proc = Popen(cmd, **kwargs)
      File "/root/anaconda3/lib/python3.7/subprocess.py", line 775, in __init__
        restore_signals, start_new_session)
      File "/root/anaconda3/lib/python3.7/subprocess.py", line 1522, in _execute_child
        raise child_exception_type(errno_num, err_msg, err_filename)
    FileNotFoundError: [Errno 2] No such file or directory: 'ijskernel': 'ijskernel'
[W 19:01:26.153 NotebookApp] Unhandled error
[E 19:01:26.154 NotebookApp] {
      "Host": "192.168.1.55:8123",
      "Connection": "keep-alive",
      "Content-Length": "94",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "X-Requested-With": "XMLHttpRequest",
      "X-Xsrftoken": "2|2449196c|91c75207fbf9ed069018bb269cfd9fa1|1600328080",
      "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36",
      "Content-Type": "application/json",
      "Origin": "http://192.168.1.55:8123",
      "Referer": "http://192.168.1.55:8123/notebooks/Untitled.ipynb",
      "Accept-Encoding": "gzip, deflate",
      "Accept-Language": "zh-CN,zh;q=0.9",
      "Cookie": "username-192-168-1-55-8123=\"2|1:0|10:1600157322|26:username-192-168-1-55-8123|44:OTdkYmE4MjM3MTQ1NDllYWJkNjk5NWUxNDI5ODRlZWY=|8e9606b8b252db20e576ad56d15e47f802fdb36dae166fa4e804cb88385feab6\"; _xsrf=2|2449196c|91c75207fbf9ed069018bb269cfd9fa1|1600328080"

**Comment by pcamateur** [comment]
I don't know what happend,I need some help,thanks

**Comment by pcamateur** [comment]
OS: CentOS Linux 8 (Core) x86_64
Kernel: 4.18.0-147.8.1.el8_1.x86_64

**Comment by n-riesco** [comment]
The error message is telling us that the IJavascript kernel hasn't been installed in your `PATH`. As a workaround, you could re-install the kernelspec using full paths, i.e.:

```
$ ijsinstall --spec-path=full
```

**Comment by n-riesco** [comment]
Closing for lack of feedback and being unable to reproduce.
