### ISSUE TITLE
IJavascript fails to install using jupyter_core 4.9.1

### ISSUE THREAD

**Issue by kcool11** [n-riesco/ijavascript#255]
When running 'Jupiter notebook', I could see the 'JavaScript (node. JS)' kernel, but when I tried to run "console. Log (Hello I JavaScript)" to celebrate, unfortunately I got the kernel hang up

I think the problem is that the "warning" information is not processed when "node ijsinstall" is executed, so I try "node ijsinstall [notebook]" and "node ijsinstall -- notebook", but they are invalid. I try to“ https://www.npmjs.com/package/ijavascript ”Looking for effective information, but it doesn't work. Can you help me?

```
D:\Web\tools\Node_js\node-v14.18.1-win-x64\node_modules\ijavascript\bin>node ijsinstall.js
Warning: Unable to parse Jupyter version: Selected Jupyter core packages...
IPython          : 7.29.0
ipykernel        : 6.5.0
ipywidgets       : not installed
jupyter_client   : 6.2.0
jupyter_core     : 4.9.1
jupyter_server   : 1.11.2
jupyterlab       : not installed
nbclient         : 0.5.8
nbconvert        : 6.3.0
nbformat         : 5.1.3
notebook         : 6.4.5
qtconsole        : not installed
traitlets        : 5.1.1
````

**Comment by kcool11** [comment]
more info:
![image](https://user-images.githubusercontent.com/61131784/141680223-8c79d7a6-5037-4368-b87a-8a194eadb2d8.png)

```
Traceback (most recent call last):
  File "C:\Users\King\AppData\Local\Programs\Python\Python39-32\lib\site-packages\tornado\web.py", line 1704, in _execute
    result = await result
  File "C:\Users\King\AppData\Local\Programs\Python\Python39-32\lib\site-packages\tornado\gen.py", line 769, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "C:\Users\King\AppData\Local\Programs\Python\Python39-32\lib\site-packages\notebook\services\sessions\handlers.py", line 74, in post
    model = yield maybe_future(
  File "C:\Users\King\AppData\Local\Programs\Python\Python39-32\lib\site-packages\tornado\gen.py", line 762, in run
    value = future.result()
  File "C:\Users\King\AppData\Local\Programs\Python\Python39-32\lib\site-packages\tornado\gen.py", line 769, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "C:\Users\King\AppData\Local\Programs\Python\Python39-32\lib\site-packages\notebook\services\sessions\sessionmanager.py", line 98, in create_session
    kernel_id = yield self.start_kernel_for_session(session_id, path, name, type, kernel_name)
  File "C:\Users\King\AppData\Local\Programs\Python\Python39-32\lib\site-packages\tornado\gen.py", line 762, in run
    value = future.result()
  File "C:\Users\King\AppData\Local\Programs\Python\Python39-32\lib\site-packages\tornado\gen.py", line 769, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "C:\Users\King\AppData\Local\Programs\Python\Python39-32\lib\site-packages\notebook\services\sessions\sessionmanager.py", line 110, in start_kernel_for_session
    kernel_id = yield maybe_future(
  File "C:\Users\King\AppData\Local\Programs\Python\Python39-32\lib\site-packages\tornado\gen.py", line 762, in run
    value = future.result()
  File "C:\Users\King\AppData\Local\Programs\Python\Python39-32\lib\site-packages\notebook\services\kernels\kernelmanager.py", line 176, in start_kernel
    kernel_id = await maybe_future(self.pinned_superclass.start_kernel(self, **kwargs))
  File "C:\Users\King\AppData\Local\Programs\Python\Python39-32\lib\site-packages\jupyter_client\utils.py", line 25, in wrapped
    return loop.run_until_complete(coro(*args, **kwargs))
  File "C:\Users\King\AppData\Local\Programs\Python\Python39-32\lib\site-packages\nest_asyncio.py", line 70, in run_until_complete
    return f.result()
  File "C:\Users\King\AppData\Local\Programs\Python\Python39-32\lib\asyncio\futures.py", line 201, in result
    raise self._exception
  File "C:\Users\King\AppData\Local\Programs\Python\Python39-32\lib\asyncio\tasks.py", line 256, in __step
    result = coro.send(None)
  File "C:\Users\King\AppData\Local\Programs\Python\Python39-32\lib\site-packages\jupyter_client\multikernelmanager.py", line 214, in _async_start_kernel
    self._add_kernel_when_ready(kernel_id, km, ensure_async(km.start_kernel(**kwargs)))
  File "C:\Users\King\AppData\Local\Programs\Python\Python39-32\lib\site-packages\jupyter_client\utils.py", line 25, in wrapped
    return loop.run_until_complete(coro(*args, **kwargs))
  File "C:\Users\King\AppData\Local\Programs\Python\Python39-32\lib\site-packages\nest_asyncio.py", line 70, in run_until_complete
    return f.result()
  File "C:\Users\King\AppData\Local\Programs\Python\Python39-32\lib\asyncio\futures.py", line 201, in result
    raise self._exception
  File "C:\Users\King\AppData\Local\Programs\Python\Python39-32\lib\asyncio\tasks.py", line 256, in __step
    result = coro.send(None)
  File "C:\Users\King\AppData\Local\Programs\Python\Python39-32\lib\site-packages\jupyter_client\manager.py", line 376, in _async_start_kernel
    self.kernel = await ensure_async(self._launch_kernel(kernel_cmd, **kw))
  File "C:\Users\King\AppData\Local\Programs\Python\Python39-32\lib\site-packages\jupyter_client\utils.py", line 25, in wrapped
    return loop.run_until_complete(coro(*args, **kwargs))
  File "C:\Users\King\AppData\Local\Programs\Python\Python39-32\lib\site-packages\nest_asyncio.py", line 70, in run_until_complete
    return f.result()
  File "C:\Users\King\AppData\Local\Programs\Python\Python39-32\lib\asyncio\futures.py", line 201, in result
    raise self._exception
  File "C:\Users\King\AppData\Local\Programs\Python\Python39-32\lib\asyncio\tasks.py", line 256, in __step
    result = coro.send(None)
  File "C:\Users\King\AppData\Local\Programs\Python\Python39-32\lib\site-packages\jupyter_client\manager.py", line 276, in _async_launch_kernel
    return launch_kernel(kernel_cmd, **kw)
  File "C:\Users\King\AppData\Local\Programs\Python\Python39-32\lib\site-packages\jupyter_client\launcher.py", line 157, in launch_kernel
    proc = Popen(cmd, **kwargs)
  File "C:\Users\King\AppData\Local\Programs\Python\Python39-32\lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\King\AppData\Local\Programs\Python\Python39-32\lib\subprocess.py", line 1420, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] 系统找不到指定的文件。
```

**Comment by n-riesco** [comment]
I'll release a fix ASAP. I need to update [this line](https://github.com/n-riesco/ijavascript/blob/b089cf154b0f1366dd64fd4820faa6c7ad05b169/bin/rc.js#L435).

**Comment by kcool11** [comment]
thanks for your help,I've solved it

**Comment by KOMNOOB** [comment]
Bro what i have to do tell me ?

**Comment by n-riesco** [comment]
@KOMNOOB Install the latest version. E.g.:

```
npm unsinstall -g ijavascript
npm install -g ijavascript
ijsintall
```

**Comment by n-riesco** [comment]
@KOMNOOB And if you want to check whether you are running the latest version, the output of running:

```
ijsinstall -version
```

should be `5.2.1`.

**Comment by KOMNOOB** [comment]
ijsinstall same thing happened 
![image](https://user-images.githubusercontent.com/92045934/143530239-abc5a0af-ed54-4785-8eb9-a29a4337cef1.png)

**Comment by n-riesco** [comment]
@KOMNOOB Sorry I mistyped that, please, use a double dash:

```
ijsinstall --version
```
