### ISSUE TITLE
Unable to run in Ubuntu WSL2 Visual Studio Code (`spawn ijskernel ENOENT`)

### ISSUE THREAD

**Issue by hyoretsu** [n-riesco/ijavascript#275]
error 16:19:58.618: Error in execution (get message for cell) [i [Error]: 
	at new r (/home/hyoretsu/.vscode-server/extensions/ms-toolsai.jupyter-2022.8.1002431955/out/extension.node.js:17:33542)
	at new o (/home/hyoretsu/.vscode-server/extensions/ms-toolsai.jupyter-2022.8.1002431955/out/extension.node.js:2:1976517)
	at new i (/home/hyoretsu/.vscode-server/extensions/ms-toolsai.jupyter-2022.8.1002431955/out/extension.node.js:2:1957914)
	at T.launch (/home/hyoretsu/.vscode-server/extensions/ms-toolsai.jupyter-2022.8.1002431955/out/extension.node.js:2:2336378)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (node:internal/process/task_queues:96:5)

Error: spawn ijskernel ENOENT
	at Process.ChildProcess._handle.onexit (node:internal/child_process:283:19)
	at onErrorNT (node:internal/child_process:478:16)
	at processTicksAndRejections (node:internal/process/task_queues:83:21)] {
  category: 'unknown',
  originalException: [Error: spawn ijskernel ENOENT
  	at Process.ChildProcess._handle.onexit (node:internal/child_process:283:19)
  	at onErrorNT (node:internal/child_process:478:16)
  	at processTicksAndRejections (node:internal/process/task_queues:83:21)] {
    errno: -2,
    code: 'ENOENT',
    syscall: 'spawn ijskernel',
    path: 'ijskernel',
    spawnargs: [
      '--hide-undefined',
      '/home/hyoretsu/.local/share/jupyter/runtime/kernel-v2-217118CbVazm91XrGt.json',
      '--protocol=5.1'
    ]
  },
  kernelConnectionMetadata: {
    kind: 'startUsingLocalKernelSpec',
    kernelSpec: {
      specFile: '/home/hyoretsu/.local/share/jupyter/kernels/javascript/kernel.json',
      interpreterPath: undefined,
      isRegisteredByVSC: undefined,
      name: 'javascript',
      argv: [Array],
      language: 'javascript',
      executable: 'ijskernel',
      display_name: 'JavaScript (Node.js)',
      metadata: [Object],
      env: undefined,
      interrupt_mode: undefined
    },
    interpreter: undefined,
    id: '.javascript./ijskernel./.ijskernel#--hide-undefined#{connection_file}#--protocol=5.1'
  },
  stdErr: '\n\n'
}

**Comment by lxl0506** [comment]
您好，攀枝花市文广旅局人事科已收到你的邮件！

**Comment by n-riesco** [comment]
It looks like `ijskernel` isn't in your `PATH`. I'd try and install the kernel spec with full paths, i.e.:

```
ijsinstall --spec-path=full
```

**Comment by hyoretsu** [comment]
Tyvm, it worked.
