### ISSUE TITLE
Java script kernel stops working in Jupyter Lab

### ISSUE THREAD

**Issue by iacisme** [n-riesco/ijavascript#283]
Hi;

Whenever I try to create a `js` notebook, the kernel crashes. The following is the server log:

```
[I 2023-05-28 21:52:57.091 ServerApp] Creating new notebook in 
[I 2023-05-28 21:52:57.472 ServerApp] Kernel started: 98f3eec7-39f3-4cda-b1f9-164196125277
node:internal/modules/cjs/loader:1280
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: /snap/core20/current/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /usr/local/lib/node_modules/ijavascript/node_modules/zeromq/prebuilds/linux-x64/node.abi93.node)
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1280:18)
    at Module.load (node:internal/modules/cjs/loader:1074:32)
    at Function.Module._load (node:internal/modules/cjs/loader:909:12)
    at Module.require (node:internal/modules/cjs/loader:1098:19)
    at require (node:internal/modules/cjs/helpers:108:18)
    at load (/usr/local/lib/node_modules/ijavascript/node_modules/node-gyp-build/node-gyp-build.js:22:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/ijavascript/node_modules/zeromq/binding.js:1:43)
    at Module._compile (node:internal/modules/cjs/loader:1196:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1250:10)
    at Module.load (node:internal/modules/cjs/loader:1074:32) {
  code: 'ERR_DLOPEN_FAILED'
}
[I 2023-05-28 21:53:00.463 ServerApp] AsyncIOLoopKernelRestarter: restarting kernel (1/5), new random ports
node:internal/modules/cjs/loader:1280
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: /snap/core20/current/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /usr/local/lib/node_modules/ijavascript/node_modules/zeromq/prebuilds/linux-x64/node.abi93.node)
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1280:18)
    at Module.load (node:internal/modules/cjs/loader:1074:32)
    at Function.Module._load (node:internal/modules/cjs/loader:909:12)
    at Module.require (node:internal/modules/cjs/loader:1098:19)
    at require (node:internal/modules/cjs/helpers:108:18)
    at load (/usr/local/lib/node_modules/ijavascript/node_modules/node-gyp-build/node-gyp-build.js:22:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/ijavascript/node_modules/zeromq/binding.js:1:43)
    at Module._compile (node:internal/modules/cjs/loader:1196:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1250:10)
    at Module.load (node:internal/modules/cjs/loader:1074:32) {
  code: 'ERR_DLOPEN_FAILED'
}
```
I've tried installing `libc6` using `apt`:

```
sudo apt install libc6
```

But it says I already have it installed. I'm not well versed on `snap` installs. I tried installing it using the following:

```
sudo snap install libc6
```
But it can't find that package.

Can someone please let me know how to resolve?

Here is my jupyter details:

```
IPython          : 8.12.0
ipykernel        : 6.22.0
ipywidgets       : 8.0.6
jupyter_client   : 8.2.0
jupyter_core     : 5.3.0
jupyter_server   : 2.5.0
jupyterlab       : 3.6.3
nbclient         : 0.7.3
nbconvert        : 7.3.1
nbformat         : 5.8.0
notebook         : 6.5.4
qtconsole        : not installed
traitlets        : 5.9.0
```

Thank you!

**Comment by n-riesco** [comment]
I see in those logs that JupyterLab is a snap installation. I'm guessing the failure to launch the IJavascript kernel may be the result of JupyterLab and your installation of node.js using different glibc versions.

I'd try to reinstall the IJavascript kernelspec using full paths, like this:

```sh
ijsinstall --spec-path=full
```

If this doesn't work, the IJavascript kernel may also fail if node.js has been updated after installing the kernel. If this is the case, uninstalling and install ijavascript may fix the problem.

```sh
npm uninstall -g ijavascript
npm install -g ijavascript
```

If none of the above works for you, I will need to know your OS and how JupyterLab and iJavascript were installed (so that I can reproduce the issue).

**Comment by iacisme** [comment]
Hi;

Thanks for the response, I tried your recommendations but they didn't work. However; I believe it's issues with my system set up.

I'm realizing that I didn't follow the installation instructions correctly so I need to fix that first. I'll follow up with a report after I uninstall and then re-install everything.

Cheers!

**Comment by iacisme** [comment]
Hi;

I re-did the installation making sure I followed the instructions this time, it works.

Thanks for helping trouble-shoot.
