### ISSUE TITLE
Installation failed on Ubuntu 12.04

### ISSUE THREAD

**Issue by yoavram** [n-riesco/ijavascript#3]
Ubuntu 12.04 64-bit, just installed `npm`, IPython and Python already installed.
Getting this error:
```
user@Ubuntu1:~$ sudo npm install ijavascript
npm http GET https://registry.npmjs.org/ijavascript

npm ERR! Error: failed to fetch from registry: ijavascript
npm ERR!     at /usr/share/npm/lib/utils/npm-registry-client/get.js:139:12
npm ERR!     at cb (/usr/share/npm/lib/utils/npm-registry-client/request.js:31:9)
npm ERR!     at Request._callback (/usr/share/npm/lib/utils/npm-registry-client/request.js:136:18)
npm ERR!     at Request.callback (/usr/lib/nodejs/request/main.js:119:22)
npm ERR!     at Request.<anonymous> (/usr/lib/nodejs/request/main.js:212:58)
npm ERR!     at Request.emit (events.js:88:20)
npm ERR!     at ClientRequest.<anonymous> (/usr/lib/nodejs/request/main.js:412:12)
npm ERR!     at ClientRequest.emit (events.js:67:17)
npm ERR!     at HTTPParser.onIncoming (http.js:1261:11)
npm ERR!     at HTTPParser.onHeadersComplete (http.js:102:31)
npm ERR! You may report this log at:
npm ERR!     <http://bugs.debian.org/npm>
npm ERR! or use
npm ERR!     reportbug --attach /home/user/npm-debug.log npm
npm ERR! 
npm ERR! System Linux 3.2.0-65-generic
npm ERR! command "node" "/usr/bin/npm" "install" "ijavascript"
npm ERR! cwd /home/user
npm ERR! node -v v0.6.12
npm ERR! npm -v 1.1.4
npm ERR! message failed to fetch from registry: ijavascript
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/user/npm-debug.log
npm not ok
```
and then:
```
user@Ubuntu1:~$ cat /home/user/npm-debug.log
info it worked if it ends with ok
verbose cli [ 'node', '/usr/bin/npm', 'install', 'ijavascript' ]
info using npm@1.1.4
info using node@v0.6.12
verbose config file /home/user/.npmrc
verbose config file /usr/etc/npmrc
verbose config file /usr/share/npm/npmrc
verbose cache add [ 'ijavascript', null ]
silly cache add: name, spec, args [ undefined, 'ijavascript', [ 'ijavascript', null ] ]
verbose parsed url { pathname: 'ijavascript',
verbose parsed url   path: 'ijavascript',
verbose parsed url   href: 'ijavascript' }
verbose addNamed [ 'ijavascript', '' ]
verbose addNamed [ null, '' ]
silly name, range, hasData [ 'ijavascript', '', false ]
verbose raw, before any munging ijavascript
verbose url resolving [ 'https://registry.npmjs.org/', './ijavascript' ]
verbose url resolved https://registry.npmjs.org/ijavascript
http GET https://registry.npmjs.org/ijavascript
ERR! Error: failed to fetch from registry: ijavascript
ERR!     at /usr/share/npm/lib/utils/npm-registry-client/get.js:139:12
ERR!     at cb (/usr/share/npm/lib/utils/npm-registry-client/request.js:31:9)
ERR!     at Request._callback (/usr/share/npm/lib/utils/npm-registry-client/request.js:136:18)
ERR!     at Request.callback (/usr/lib/nodejs/request/main.js:119:22)
ERR!     at Request.<anonymous> (/usr/lib/nodejs/request/main.js:212:58)
ERR!     at Request.emit (events.js:88:20)
ERR!     at ClientRequest.<anonymous> (/usr/lib/nodejs/request/main.js:412:12)
ERR!     at ClientRequest.emit (events.js:67:17)
ERR!     at HTTPParser.onIncoming (http.js:1261:11)
ERR!     at HTTPParser.onHeadersComplete (http.js:102:31)
ERR! You may report this log at:
ERR!     <http://bugs.debian.org/npm>
ERR! or use
ERR!     reportbug --attach /home/user/npm-debug.log npm
ERR! 
ERR! System Linux 3.2.0-65-generic
ERR! command "node" "/usr/bin/npm" "install" "ijavascript"
ERR! cwd /home/user
ERR! node -v v0.6.12
ERR! npm -v 1.1.4
ERR! message failed to fetch from registry: ijavascript
verbose exit [ 1, true ]
```

**Comment by n-riesco** [comment]
It looks like a problem with with `npm` in your system. To help me understand it, could you install another package? For example, `zmq`:

```sh
sudo npm install -g zmq
```

By the way, if you want to use sudo and install globally, then you have to add the flag `-g`, as shown above.

In the meantime, I will try to reproduce the problem here on a VM with Ubuntu 12.04.

**Comment by yoavram** [comment]
You are right, it's an `npm` problem:
```
user@Ubuntu1:~$ sudo npm install -g zmq
[sudo] password for user: 
npm http GET https://registry.npmjs.org/zmq

npm ERR! Error: failed to fetch from registry: zmq
npm ERR!     at /usr/share/npm/lib/utils/npm-registry-client/get.js:139:12
npm ERR!     at cb (/usr/share/npm/lib/utils/npm-registry-client/request.js:31:9)
npm ERR!     at Request._callback (/usr/share/npm/lib/utils/npm-registry-client/request.js:136:18)
npm ERR!     at Request.callback (/usr/lib/nodejs/request/main.js:119:22)
npm ERR!     at Request.<anonymous> (/usr/lib/nodejs/request/main.js:212:58)
npm ERR!     at Request.emit (events.js:88:20)
npm ERR!     at ClientRequest.<anonymous> (/usr/lib/nodejs/request/main.js:412:12)
npm ERR!     at ClientRequest.emit (events.js:67:17)
npm ERR!     at HTTPParser.onIncoming (http.js:1261:11)
npm ERR!     at HTTPParser.onHeadersComplete (http.js:102:31)
npm ERR! You may report this log at:
npm ERR!     <http://bugs.debian.org/npm>
npm ERR! or use
npm ERR!     reportbug --attach /home/user/npm-debug.log npm
npm ERR! 
npm ERR! System Linux 3.2.0-65-generic
npm ERR! command "node" "/usr/bin/npm" "install" "-g" "zmq"
npm ERR! cwd /home/user
npm ERR! node -v v0.6.12
npm ERR! npm -v 1.1.4
npm ERR! message failed to fetch from registry: zmq
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/user/npm-debug.log
npm not ok
```
but it's a new `npm` that I installed with `apt-get` today...

**Comment by n-riesco** [comment]
I've found [this issue](https://github.com/npm/npm/issues/2119) in `npm`, which was reported in 2012.

It suggests to run this command as a workaround:

```sh
npm config set registry "http://registry.npmjs.org/"
```

The above command tells `npm` to use HTTP instead fo HTTPS.

**Comment by yoavram** [comment]
So I did this (some of it from [here](http://ianrumford.github.io/blog/2012/09/12/installing-zeromq-2-dot-2-0-with-the-ruby-gem-on-ubuntu-12-dot-04/)):
```
sudo apt-get install nodejs
sudo apt-get install uuid uuid-dev uuid-runtime
sudo npm install zmq -g
sudo npm install ijavascript -g
```
and it worked.

**Comment by n-riesco** [comment]
Unfortunately, those instructions didn't work in a VM running ubuntu 12.04.5.

I've updated README.md with instructions to upgrade `node.js` and `ipython` to their latest versions.

Note, though, that running under the latest version of ipython (version 3.0.0b1), ijavascript is affected by [issue #1](https://github.com/n-riesco/ijavascript/issues/1).
