### ISSUE TITLE
Install error using Ubuntu 14.04 and Anaconda

### ISSUE THREAD

**Issue by Coldmooon** [n-riesco/ijavascript#35]
I just follow the instruction to install ijavascript.

```
sudo apt-get install nodejs-legacy npm libzmq-dev
sudo npm install -g ijavascript
```

Since I've installed `anaconda python` and `ipython-notebook`, I skipped `ipython` and `ipython-notebook` in the first step.
In the second step, I've got the error below.

```
npm http GET https://registry.npmjs.org/ijavascript
npm http 304 https://registry.npmjs.org/ijavascript
npm http GET https://registry.npmjs.org/jmp
npm http GET https://registry.npmjs.org/node-uuid
npm http GET https://registry.npmjs.org/zmq
npm http 304 https://registry.npmjs.org/node-uuid
npm http 304 https://registry.npmjs.org/jmp
npm http 304 https://registry.npmjs.org/zmq
npm http GET https://registry.npmjs.org/bindings
npm http GET https://registry.npmjs.org/nan
npm http 304 https://registry.npmjs.org/bindings
npm http 304 https://registry.npmjs.org/nan

> zmq@2.11.1 install /usr/local/lib/node_modules/ijavascript/node_modules/zmq
> node-gyp rebuild

Traceback (most recent call last):
  File "/usr/share/node-gyp/gyp/gyp", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/home/coldmoon/anaconda/lib/python2.7/site-packages/setuptools-17.0-py2.7.egg/pkg_resources/__init__.py", line 3074, in <module>
  File "/home/coldmoon/anaconda/lib/python2.7/site-packages/setuptools-17.0-py2.7.egg/pkg_resources/__init__.py", line 3060, in _call_aside
  File "/home/coldmoon/anaconda/lib/python2.7/site-packages/setuptools-17.0-py2.7.egg/pkg_resources/__init__.py", line 3087, in _initialize_master_working_set
  File "/home/coldmoon/anaconda/lib/python2.7/site-packages/setuptools-17.0-py2.7.egg/pkg_resources/__init__.py", line 645, in _build_master
  File "/home/coldmoon/anaconda/lib/python2.7/site-packages/setuptools-17.0-py2.7.egg/pkg_resources/__init__.py", line 946, in require
  File "/home/coldmoon/anaconda/lib/python2.7/site-packages/setuptools-17.0-py2.7.egg/pkg_resources/__init__.py", line 833, in resolve
pkg_resources.DistributionNotFound: The 'gyp==0.1' distribution was not found and is required by the application
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/share/node-gyp/lib/configure.js:431:16)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:797:12)
gyp ERR! System Linux 3.16.0-30-generic
gyp ERR! command "nodejs" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/ijavascript/node_modules/zmq
gyp ERR! node -v v0.10.25
gyp ERR! node-gyp -v v0.10.10
gyp ERR! not ok 
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian

npm ERR! weird error 1
npm ERR! not ok code 0
```

I can't figure out what's wrong. Can anyone help me?  Many thanks~!

**Comment by n-riesco** [comment]
It looks like a problem with the installation of `Node.js`.

What linux distribution are you using?
Could you post the output of runnning `lsb_release -sd`?

**Comment by n-riesco** [comment]
I suspect the local installation of anaconda is in conflict with gyp installed globally.

As a workaround, I would suggest that you install ijavascript from the root account:

```sh
sudo su
npm install -g ijavascript
exit
```

**Comment by Coldmooon** [comment]
Thanks ,@n-riesco n-riesco 
I'm using Ubuntu 14.04
```
$ lsb_release -sd
Ubuntu 14.04.2 LTS
```

I followed what you said. But I still got the same error.
Besides, I tried to find if there is the `/usr/local/lib/node_modules/ijavascript` directory.
```
$ find /usr/local/lib/node_modules/ijavascript
find: `/usr/local/lib/node_modules/ijavascript': No such file or directory
```
There isn't `ijavascript` directory. Is this the reason ? Do I need to download the ijavascript from this repository and put it in the directory `/usr/local/lib/node_modules/` ?

**Comment by n-riesco** [comment]
That's unexpected. Could you run my instructions again and copy and paste everything here?
Please, make sure to include the flag `-g`:

```sh
sudo su
npm install -g ijavascript
exit
 ```

This is what I get:

```
# npm install -g ijavascript
\
> zmq@2.11.1 install /usr/local/lib/node_modules/ijavascript/node_modules/zmq
> node-gyp rebuild

make: Entering directory `/usr/local/lib/node_modules/ijavascript/node_modules/zmq/build'
  CXX(target) Release/obj.target/zmq/binding.o
  SOLINK_MODULE(target) Release/obj.target/zmq.node
  SOLINK_MODULE(target) Release/obj.target/zmq.node: Finished
  COPY Release/zmq.node
make: Leaving directory `/usr/local/lib/node_modules/ijavascript/node_modules/zmq/build'
/usr/local/bin/ijs -> /usr/local/lib/node_modules/ijavascript/bin/ijavascript.js
ijavascript@5.0.3 /usr/local/lib/node_modules/ijavascript
├── jmp@0.0.7
├── node-uuid@1.4.3
└── zmq@2.11.1 (bindings@1.1.1, nan@1.8.4)

```

PS: I'm travelling this week. It may take some time for me reply.

**Comment by Coldmooon** [comment]
```
coldmoon@coldmoonPC:~/Downloads$ sudo su
[sudo] password for coldmoon: 
root@coldmoonPC:/home/coldmoon/Downloads# npm install -g ijavascript
npm http GET https://registry.npmjs.org/ijavascript
npm http 304 https://registry.npmjs.org/ijavascript
npm http GET https://registry.npmjs.org/jmp
npm http GET https://registry.npmjs.org/zmq
npm http GET https://registry.npmjs.org/node-uuid
npm http 304 https://registry.npmjs.org/node-uuid
npm http 304 https://registry.npmjs.org/zmq
npm http 304 https://registry.npmjs.org/jmp
npm http GET https://registry.npmjs.org/nan
npm http GET https://registry.npmjs.org/bindings
npm http 304 https://registry.npmjs.org/nan
npm http 304 https://registry.npmjs.org/bindings

> zmq@2.11.1 install /usr/local/lib/node_modules/ijavascript/node_modules/zmq
> node-gyp rebuild

Traceback (most recent call last):
  File "/usr/share/node-gyp/gyp/gyp", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/home/coldmoon/anaconda/lib/python2.7/site-packages/setuptools-17.1.1-py2.7.egg/pkg_resources/__init__.py", line 3084, in <module>
  File "/home/coldmoon/anaconda/lib/python2.7/site-packages/setuptools-17.1.1-py2.7.egg/pkg_resources/__init__.py", line 3070, in _call_aside
  File "/home/coldmoon/anaconda/lib/python2.7/site-packages/setuptools-17.1.1-py2.7.egg/pkg_resources/__init__.py", line 3097, in _initialize_master_working_set
  File "/home/coldmoon/anaconda/lib/python2.7/site-packages/setuptools-17.1.1-py2.7.egg/pkg_resources/__init__.py", line 651, in _build_master
  File "/home/coldmoon/anaconda/lib/python2.7/site-packages/setuptools-17.1.1-py2.7.egg/pkg_resources/__init__.py", line 952, in require
  File "/home/coldmoon/anaconda/lib/python2.7/site-packages/setuptools-17.1.1-py2.7.egg/pkg_resources/__init__.py", line 839, in resolve
pkg_resources.DistributionNotFound: The 'gyp==0.1' distribution was not found and is required by the application
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/share/node-gyp/lib/configure.js:431:16)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:797:12)
gyp ERR! System Linux 3.16.0-30-generic
gyp ERR! command "nodejs" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/ijavascript/node_modules/zmq
gyp ERR! node -v v0.10.25
gyp ERR! node-gyp -v v0.10.10
gyp ERR! not ok 
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm ERR! weird error 1
npm ERR! not ok code 0
root@coldmoonPC:/home/coldmoon/Downloads# 
```

The first difference between us is that in your computer, there is 
`Entering directory '/usr/local/lib/node_modules/ijavascript/node_modules/zmq/build'`
, but in my computer, there isn't `ijavascript` directory. I don't know if this is the reason.

**Comment by n-riesco** [comment]
I believe the reason why IJavascript fails to install is that `npm` uses `node-gyp`, and `node-gyp` uses `gyp`. Unfortunately, Anaconda overwrites `gyp` with a different version. What surprises me is that it seems to overwrite `gyp` for your root user too (did you use `sudo` to install Anaconda?).

Here's another workaround (a bit more involved, but I hope it'll work for your system):

1. Temporarily, rename folder `/home/coldmoon/anaconda` as `/home/coldmoon/anaconda.bak`:  
     `$ mv /home/coldmoon/anaconda /home/coldmoon/anaconda.bak`
2. Ensure Anaconda's python isn't accessible any longer:  
     `$ which python`  
     `/usr/bin/python`
3. Install IJavascript:  
    `$ sudo npm install -g ijavascript`
4. Restore Anacoda's folder:  
     `$ mv /home/coldmoon/anaconda.bak /home/coldmoon/anaconda`

I'm aware this is not ideal, but until next week I won't be able to install Anaconda in one of my VMs and come up with a solution more elegant.

**Comment by Coldmooon** [comment]
It worked! Just as you said, it's because anaconda is in conflict with gyp. I renamed anaconda and then installed ijavascript from the root account. Now is:
```
coldmoon@coldmoonPC:~$ sudo npm install -g ijavascript
[sudo] password for coldmoon: 
npm http GET https://registry.npmjs.org/ijavascript
npm http 304 https://registry.npmjs.org/ijavascript
npm http GET https://registry.npmjs.org/jmp
npm http GET https://registry.npmjs.org/zmq
npm http GET https://registry.npmjs.org/node-uuid
npm http 304 https://registry.npmjs.org/node-uuid
npm http 304 https://registry.npmjs.org/zmq
npm http 304 https://registry.npmjs.org/jmp
npm http GET https://registry.npmjs.org/nan
npm http GET https://registry.npmjs.org/bindings
npm http 304 https://registry.npmjs.org/nan
npm http 200 https://registry.npmjs.org/bindings

> zmq@2.11.1 install /usr/local/lib/node_modules/ijavascript/node_modules/zmq
> node-gyp rebuild

make: Entering directory `/usr/local/lib/node_modules/ijavascript/node_modules/zmq/build'
  CXX(target) Release/obj.target/zmq/binding.o
  SOLINK_MODULE(target) Release/obj.target/zmq.node
  SOLINK_MODULE(target) Release/obj.target/zmq.node: Finished
  COPY Release/zmq.node
make: Leaving directory `/usr/local/lib/node_modules/ijavascript/node_modules/zmq/build'
/usr/local/bin/ijs -> /usr/local/lib/node_modules/ijavascript/bin/ijavascript.js
ijavascript@5.0.3 /usr/local/lib/node_modules/ijavascript
├── jmp@0.0.7
├── node-uuid@1.4.3
└── zmq@2.11.1 (bindings@1.1.1, nan@1.8.4)
```
Thank you so much~~!

**Comment by Coldmooon** [comment]
And I did some more. I think I've found the direct reason. Now I can compile successfully without renaming anaconda folder.

1) Whether rename anaconda or not, `node-gyp` and `gyp` point to
```
coldmoon@coldmoonPC:~$ which node-gyp
/usr/local/bin/node-gyp
coldmoon@coldmoonPC:~$ ls -l /usr/local/bin/node-gyp
lrwxrwxrwx 1 root root 44  /usr/local/bin/node-gyp -> ../lib/node_modules/node-gyp/bin/node-gyp.js
```
coldmoon@coldmoonPC:~$ which gyp
/usr/bin/gyp
coldmoon@coldmoonPC:~$ ls -l /usr/bin/gyp
-rwxr-xr-x 1 root root 276  /usr/bin/gyp
```
So, `node-gyp` and `gyp` works fine. 

2) The problem seems to be python's version. In the  `/usr/bin`, there is `python` file
```
coldmoon@coldmoonPC:~$ ls -l /usr/bin/python
-rwxr-xr-x 1 root root 3781768  /usr/bin/python
```
It is the original python 2.7. At the same time, In the `.bashrc` file, anaconda python is added to $PATH
`export PATH="/home/coldmoon/anaconda/bin:$PATH"`
`coldmoon@coldmoonPC:~$ which python`
`/home/coldmoon/anaconda/bin/python`
In this case, I can compile ijavascript smoothly.

However, if I rename `/usr/bin/python` to `python-original` , make a symbolic link from `/usr/bin/python` to `/home/coldmoon/anaconda/bin/python`, and do not change anything else,  the installation fails.

So, the critical thing is if `/usr/bin/python` is origial.
Original   compilation succeeds,  third-party    compilation fails

**Comment by n-riesco** [comment]
I would advise against renaming `/usr/bin/python` (it may break python for other users).

If I understood correctly your results above, there seems to be an alternative installation of `node-gyp` on `/usr/local/`. Is this local installation part of Anaconda?

**Comment by Coldmooon** [comment]
Thanks, I won't rename `/usr/bin/python` again. 

Anaconda is in my `home` directory.  I remember I installed anaconda from the root account. Then 
changed the anaconda directory's owner to me. It's a little complicated...

What do you mean by `an alternative installation of node-gyp on /usr/local/` ?  I don't understand the sentence. This is the list of `node-gyp` in `/usr/local/`
```
coldmoon@coldmoonPC:/usr/local$ find $PWD -name "*node-gyp*"
/usr/local/bin/node-gyp
/usr/local/lib/node_modules/node-gyp
/usr/local/lib/node_modules/node-gyp/bin/node-gyp.js
/usr/local/lib/node_modules/node-gyp/lib/node-gyp.js
```

**Comment by n-riesco** [comment]
In my computer, I get:
```
$ ls -l $(which gyp)
-rwxr-xr-x 1 root root 276 Mar 18  2014 /usr/bin/gyp
$ ls -l $(which node-gyp)
lrwxrwxrwx 1 root root 33 Oct 22  2013 /usr/bin/node-gyp -> ../share/node-gyp/bin/node-gyp.js
```

**Comment by Coldmooon** [comment]
gyp is the same
```
coldmoon@coldmoonPC:~$ ls -l $(which gyp)
-rwxr-xr-x 1 root root 276  Mar 19  2014 /usr/bin/gyp
```

node-gyp is different:
```
coldmoon@coldmoonPC:~$ ls -l $(which node-gyp)
lrwxrwxrwx 1 root root 44  Jun 22 18:56 /usr/local/bin/node-gyp -> ../lib/node_modules/node-gyp/bin/node-gyp.js
```
```
coldmoon@coldmoonPC:~$ node-gyp -v
v2.0.1
coldmoon@coldmoonPC:~$ md5sum /usr/local/lib/node_modules/node-gyp/bin/node-gyp.js
6be5e25e1ce72a690c33779d1212115f  /usr/local/lib/node_modules/node-gyp/bin/node-gyp.js
```

**Comment by n-riesco** [comment]
I will update the documentation with instructions to install IJavascript and Anaconda on Ubuntu.

Sorry about the delay!

**Comment by rgbkrk** [comment]
The node-zmq story needs some help across projects. It would be nice if we had bundled versions of either zmq or jmp across recent versions of node, iojs, and electron (which has different headers).

**Comment by n-riesco** [comment]
The following instructions work for Anaconda2

```sh
conda install nodejs
sudo apt-get install libzmq3-dev
sudo npm install -g ijavascript
```

**Comment by zjost** [comment]
Renaming local anaconda directory and then installing also worked for me while getting the same error trying to install ZeroMQ.  So thanks!
