### ISSUE TITLE
Failed test on Node.js v0.12

### ISSUE THREAD

**Issue by n-riesco** [n-riesco/ijavascript#41]
Some tests fail when running `npm run test:4` and `npm run test:5` on the latest Docker image for Node.js v0.12:
- Testing execute_request: throw new Error('Hello, World!')
- Testing inspect_request: util.inspect

It looks like a change in the output of thrown exceptions.

```
Testing execute_request: throw new Error('Hello, World!')
Failed test execute_request: throw new Error('Hello, World!'): Observed = evalmachine.<anonymous>:1
throw new Error('Hello, World!')
      ^
Hello, World!: Expected = Hello, World!
AssertionError: Failed test execute_request: throw new Error('Hello, World!'): Observed = evalmachine.<anonymous>:1
throw new Error('Hello, World!')
      ^
Hello, World!: Expected = Hello, World!
    at Function.MessagingTestEngine.checkMessage (/ijavascript/test/index.js:624:16)
    at /ijavascript/test/index.js:638:29
    at Array.forEach (native)
    at Function.MessagingTestEngine.checkMessage (/ijavascript/test/index.js:635:42)
    at /ijavascript/test/index.js:638:29
    at Array.forEach (native)
    at Function.MessagingTestEngine.checkMessage (/ijavascript/test/index.js:635:42)
    at MessagingTestEngine._runIfPossible (/ijavascript/test/index.js:598:33)
    at MessagingTestEngine.<anonymous> (/ijavascript/test/index.js:431:22)
    at emit (events.js:118:17)
```

```
Testing inspect_request: util.inspect
Failed test inspect_request: util.inspect: Observed = evalmachine.<anonymous>:1
util
^
util is not defined: Expected = util is not defined
AssertionError: Failed test inspect_request: util.inspect: Observed = evalmachine.<anonymous>:1
util
^
util is not defined: Expected = util is not defined
    at Function.MessagingTestEngine.checkMessage (/ijavascript/test/index.js:635:16)
    at /ijavascript/test/index.js:652:29
    at Array.forEach (native)
    at Function.MessagingTestEngine.checkMessage (/ijavascript/test/index.js:646:42)
    at /ijavascript/test/index.js:652:29
    at Array.forEach (native)
    at Function.MessagingTestEngine.checkMessage (/ijavascript/test/index.js:646:42)
    at MessagingTestEngine._runIfPossible (/ijavascript/test/index.js:609:33)
    at MessagingTestEngine.<anonymous> (/ijavascript/test/index.js:442:22)
    at emit (events.js:118:17)
```

**Comment by n-riesco** [comment]
Opened an [issue](https://github.com/joyent/node/issues/25904) on the `Node.js` repository.

**Comment by n-riesco** [comment]
I've just checked and this issue isn't present in the latest Node.js v4.1.1
