### ISSUE TITLE
Kernel crashes on attempt to tab complete

### ISSUE THREAD

**Issue by itkach** [n-riesco/ijavascript#5]
Type `func` in a cell, hit Tab, observe "Dead kernel" status label appears and the following exception in ijs output:

```
[I 13:36:23.062 NotebookApp] KernelRestarter: restarting kernel (1/5)
WARNING:root:kernel be7eec2c-4bf4-4f2e-95e3-2a4de794abe6 restarted
events.js:75
      throw er; // Unhandled 'error' event
            ^
TypeError: Cannot read property 'slice' of undefined
    at parseExpression (/home/itkach/lib/node_modules/ijavascript/lib/kernel.js:291:30)
    at Kernel.complete_request (/home/itkach/lib/node_modules/ijavascript/lib/kernel.js:369:22)
    at Kernel._onMessage (/home/itkach/lib/node_modules/ijavascript/lib/kernel.js:109:33)
    at emit (events.js:108:17)
    at Socket._flush (/home/itkach/lib/node_modules/ijavascript/node_modules/zmq/lib/index.js:510:19)
    at _zmq.onReady (/home/itkach/lib/node_modules/ijavascript/node_modules/zmq/lib/index.js:193:12)
```
iojs v1.1.0, ijavascript 4.1.4, ipython 3.0.0

**Comment by n-riesco** [comment]
Thank you for reporting this ussue. I've tracked down this issue to ipython 3.0.0 using protocol version 5.0 despite ijavascript reporting the use of version 4.1. I will provide a solution soon.

**Comment by itkach** [comment]
Indeed, tab complete doesn't crash in IPython 2.2.0
